// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"starlights/app/wechatbot/internal/biz"
	"starlights/app/wechatbot/internal/conf"
	"starlights/app/wechatbot/internal/data"
	"starlights/app/wechatbot/internal/server"
	"starlights/app/wechatbot/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bot *conf.Bot, logger log.Logger, arg []interface{}) (serviceApp, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return serviceApp{}, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	openwechatBot := server.NewBotServer(bot, logger, arg)
	mainServiceApp := newApp(logger, grpcServer, httpServer, openwechatBot)
	return mainServiceApp, func() {
		cleanup()
	}, nil
}
